### ISSUE TITLE
What period should I use to calculate the volatility for another asset such as Bitcoin?

### ISSUE THREAD

**Issue by soulmachine** [robcarver17/systematictradingexamples#6]
Hi Robert, this is not an issue but actually a question.

In your code [ewmac.py#L63](https://github.com/robcarver17/systematictradingexamples/blob/master/ewmac.py#L63) you calculate the volatility with the following code:

```python
stdev_returns=pd.ewmstd(price - price.shift(1), span=vol_lookback)   
```

And you set `vol_loopback` to a constant value 25:

```python
## Shouldn't need changing
vol_lookback=25
```

At page 198 of the book "Systematic Trading" you also said:

> Rather than risk overfitting I decided on a default look-back of 25 business days, or five weeks.

What if I'm backtesting EWMAC rule for another asset such as Bitcoin?  I think I need to use a different value, right? For now I use `slow * 2` to calculate volatility, [Jupyter notebook EWMAC Strategy in Backtrader](https://github.com/soulmachine/crypto-notebooks/blob/master/backtest/backtrader-EWMAC.ipynb).

Is there a way to calculate the best `vol_lookback` ? Thanks!

Best regards

--Frank Dai

**Comment by robcarver17** [comment]
"What if I'm backtesting EWMAC rule for another asset such as Bitcoin? I think I need to use a different value, right?"

No. You can, and should, always use 25 business days. Why would it be different for other assets? Why would it be different for different trading speeds?

**Comment by soulmachine** [comment]
Thanks for your clarification!
